# 1. 들여쓰기
# 2. --- 구분

spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.126.1:1521:XE
    username: kknd
    password: 1234

server:
  port: 8080
  cache:
    ehcache:
    config: classpath:ehcache.xml

---

spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: kknd
    password: 1234

server:
  port: 8080
  cache:
    ehcache:
    config: classpath:ehcache.xml

---

spring.mvc.view:
    prefix: /WEB-INF/views/
    suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true


