# 1. 들여쓰기
# 2. --- 구분

spring:
  profiles: dev
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.126.1:1521:XE
    username: kknd
    password: 1234
  pyMenuMain:
    path: /usr/local/server/tomcat8/webapps/ROOT/WEB-INF/classes/
    saveDirPath: /usr/local/server/tomcat8/webapps/ROOT/static/html/nav/++/libLNB.html
    pythonV: python3.6

server:
  port: 80
  tomcat:
    uri-encoding: utf-8
  cache:
    ehcache:
    config: classpath:ehcache.xml

---

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: kknd
    password: 1234
  pyMenuMain:
    path: C:/springbootJSP-master/src/main/resources/
    saveDirPath: C:/springbootJSP-master/src/main/webapp/static/html/nav/++/libLNB.html
    pythonV: python

server:
  port: 80
  cache:
    ehcache:
    config: classpath:ehcache.xml

---

spring.mvc.view:
    prefix: /WEB-INF/views/
    suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true


